apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: fluentum
spec:
  version: 8.12.0
  count: 2
  elasticsearchRef:
    name: fluentum
  config:
    server.publicBaseUrl: "https://kibana.example.com"
    xpack.security.sameSiteCookies: "None"
    xpack.security.authc.providers:
      basic.basic1:
        order: 0
        hint: "For administrators"
      anonymous.anonymous1:
        order: 1
        credentials:
          username: "dviewer"
          password: "changeme"
