#!/bin/bash

# Get the directory of the current script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Source the credentials
source "$DIR/credential.sh"

# Roles for new user (comma-separated, e.g., "userrole1,userrole2")
ANONYMOUS_ROLES="viewer"

# Format roles for JSON
IFS=',' read -r -a role_array <<< "$ANONYMOUS_ROLES"
formatted_roles=$(printf '\"%s\",' "${role_array[@]}")
formatted_roles="[${formatted_roles%,}]"

# Create user in Elasticsearch
curl -X PUT "$ELASTIC_URL/_security/user/$ANONYMOUS_USERNAME" -H "Content-Type: application/json" -u "$ELASTIC_USERNAME:$ELASTIC_PASSWORD" -d "{
  \"password\" : \"$ANONYMOUS_PASSWORD\",
  \"roles\" : $formatted_roles,
  \"full_name\" : \"$ANONYMOUS_FULL_NAME\",
  \"email\" : \"$ANONYMOUS_EMAIL\"
}"

echo "Created user $ANONYMOUS_USERNAME in Elasticsearch"

# Path to your kibana.yaml file
KIBANA_YAML="$DIR/../kibana/kibana.yaml"

# Check if the Kibana YAML file exists
if [ ! -f "$KIBANA_YAML" ]; then
    echo "Kibana YAML file not found: $KIBANA_YAML"
    exit 1
fi

# Update anonymous user credentials in the Kibana YAML file
sed -i "s/username: .*/username: \"$ANONYMOUS_USERNAME\"/" $KIBANA_YAML
sed -i "s/password: .*/password: \"$ANONYMOUS_PASSWORD\"/" $KIBANA_YAML

echo "Updated anonymous user credentials in $KIBANA_YAML"

# Create index lifecycle policy
ILM_POLICY_NAME="fluentum-ilm-policy"
DATA_RETENTION="7d"

curl -X PUT "$ELASTIC_URL/_ilm/policy/$ILM_POLICY_NAME" -H "Content-Type: application/json" -u "$ELASTIC_USERNAME:$ELASTIC_PASSWORD" -d "{
  \"policy\": {
    \"_meta\": {
      \"description\": \"Default Fluentum ILM Policy\",
      \"project\": {
        \"name\": \"fluentum\",
        \"department\": \"fluentum\"
      }
    },
    \"phases\": {
      \"delete\": {
        \"min_age\": \"$DATA_RETENTION\",
        \"actions\": {
          \"delete\": {}
        }
      }
    }
  }
}"

echo "Default index lifecycle policy created with name: $ILM_POLICY_NAME"

# Create index template and assign to index lifecycle policy
INDEX_TEMPLATE_NAME="fluentum-index-template"
FLUENTUM_INDEX_PATTERN="fluentum-*"
LOGS_INDEX_PATTERN="logs-*"  # Used for index that generated by internal connector

curl -X PUT "$ELASTIC_URL/_index_template/$INDEX_TEMPLATE_NAME" -H "Content-Type: application/json" -u "$ELASTIC_USERNAME:$ELASTIC_PASSWORD" -d "{
  \"index_patterns\": [\"$FLUENTUM_INDEX_PATTERN\", \"$LOGS_INDEX_PATTERN\"],
  \"template\": {
    \"settings\": {
      \"index.lifecycle.name\": \"$ILM_POLICY_NAME\"
    }
  }
}"

echo "Default index template created"
